### ISSUE TITLE
Unintended replacement in playbook vars dictionary

### ISSUE THREAD

**Issue by tanji** [zerwes/ansible-fqcn-converter#12]
We have the following vars list in an ansible playbook:

```
  vars:
    haproxy_version: "2.2"
    deploy: true
    combined: true
    haproxy_mode_http: true
    crt_list: "/etc/haproxy/crt-list.txt"
    domains:
      - domain: "prod.xxx.com"
        cert: "combined"
        backend: "prod"
```

fcqn-fixer is replacing `- domain : "prod.xxx.com"` by `- theforeman.foreman.domain: "prod.xxx.com"`

Suggestion is to ignore every child under `vars:` since there wont be any tasks in there anyway
