### ISSUE TITLE
vars at task level break detection of the next task

### ISSUE THREAD

**Issue by zerwes** [zerwes/ansible-fqcn-converter#31]
example play:
```yaml
---

- name: test file 1
  file:
    path: /a/b/c/1

- name: command with vars
  command: echo
  vars:
    ansible_ssh_pipelining: true

- name: test file 2
  file:
    path: /a/b/c/2

- name: test file 3
  file:
    path: /a/b/c/3
```
the `file` module name in task *test file 2* will not be converted (because not matched as task)

```yaml
± ./fqcn-fixer.py -f testfile.yml
loading fqcn map from /home/admzerwes/git/ansible-fqcn-converter/fqcn.yml ...
parsing file /home/admzerwes/git/ansible-fqcn-converter/testfile.yml ...*...*....*.
--- a/testfile.yml
+++ b/testfile.yml
@@ -1,11 +1,12 @@
 ---
 
 - name: test file 1
-  file:
+  ansible.builtin.file:
     path: /a/b/c/1
 
 - name: command with vars
-  command: echo
+  # possible ambiguous replacement: command : ansible.builtin.command | community.ciscosmb.command | community.routeros.command
+  ansible.builtin.command: echo
   vars:
     ansible_ssh_pipelining: true
 
@@ -14,5 +15,5 @@
     path: /a/b/c/2
 
 - name: test file 3
-  file:
+  ansible.builtin.file:
     path: /a/b/c/3

**Comment by zerwes** [comment]
error will occur only if the `vars` tag is the last
```yaml
- name: command with vars
  vars:
    ansible_ssh_pipelining: true
  command: echo
```
this will convert as expected
