### ISSUE TITLE
Script is converting playbook top level commands e.g. gather_facts

### ISSUE THREAD

**Issue by ryaner** [zerwes/ansible-fqcn-converter#6]
Example playbook
```
- name: FQCN test playbook
  hosts: localhost
  gather_facts: false
  tasks:
```
Results in the `gather_facts` block from being converted. Items up at this level should not be using FQCNs and result in errors if running the playbook
```
ERROR! 'ansible.builtin.gather_facts' is not a valid attribute for a Play
```

This could be somewhat related to #5 as on the current version we aren't seeing anything valid converted, even items in the top level tasks block.
